name: test
on:
  workflow_dispatch:
    inputs:
      aaaa:
        type: string
      bbb:
        type: string
      ccc:
        type: string
      ddd:
        type: string
      eee:
        type: boolean
      eeekk:
        type: boolean
        default: true
        required: true
      fff:
        type: choice
        options:
          - option1
          - option2
          - option3
      ggg:
        type: number
        required: true



jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Show summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          # configuration

          Configured with:

          `\`\`json
          $(cat <<EOJ | jq --sort-keys .
          ${{ toJSON(inputs) }}
          EOJ
          )
          `\`\`
          EOF

        
